Thank you very much for testing our software and creating an issue!

1 - Check if your issue was not already reported.

2 - Please, provide the following information (when applicable):

- Allure version
- Test framework and the Allure plugin used to generate the result folder (e.g. Pytest and allure-pytest)
- The exception traceback
- The test result files/folder you tried to use with allure-docx.
